<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Waystone.Monads</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Waystone.Monads.Extensions.Logging\Waystone.Monads.Extensions.Logging.csproj"/>
        <ProjectReference Include="..\..\src\Waystone.Monads.FluentValidation\Waystone.Monads.FluentValidation.csproj"/>
        <ProjectReference Include="..\..\src\Waystone.Monads.Shouldly\Waystone.Monads.Shouldly.csproj"/>
        <ProjectReference Include="..\..\src\Waystone.Monads\Waystone.Monads.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Shouldly"/>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="AutoFixture"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="NSubstitute.Analyzers.CSharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3"/>
    </ItemGroup>

    <Import Project="..\..\src\Waystone.Monads.Shouldly.Analyzers\Waystone.Monads.Shouldly.Analyzers.props"/>

</Project>
