namespace Waystone.Monads.SourceGenerators.ErrorCodes;

using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

internal static class ErrorCodeCatalogWriter
{
    public const string NamesClass = "Names";
    public const string CodesClass = "Codes";
    public const string ErrorsClass = "Errors";

    private const string ErrorCodeType =
        "global::Waystone.Monads.Results.Errors.ErrorCode";

    private const string ErrorType =
        "global::Waystone.Monads.Results.Errors.Error";

    private const string AutoGeneratedHeader = "// <auto-generated/>";

    private const string MessageParamDoc =
        "/// <param name=\"message\">The message describing this occurrence of the error. Trimmed of surrounding whitespace; a message that is null, empty or whitespace is replaced by the fallback configured through <c>MonadOptions.UseFallbackErrorMessage</c> rather than rejected.</param>";

    public static string Emit(
        INamedTypeSymbol enumType,
        string catalogName,
        IReadOnlyList<IFieldSymbol> members,
        ErrorCodeFormat format)
    {
        string qualified =
            enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        string @namespace = enumType.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : enumType.ContainingNamespace.ToDisplayString();

        var writer = new Writer();

        writer.Line(0, AutoGeneratedHeader);
        writer.Blank();

        var depth = 0;

        if (@namespace.Length > 0)
        {
            writer.Line(0, $"namespace {@namespace}");
            writer.Line(0, "{");
            depth = 1;
        }

        writer.Line(
            depth,
            $"/// <summary>The error code names, error codes and error factories of <c>{qualified}</c>.</summary>");

        writer.Line(
            depth,
            $"{AccessibilityOf(enumType)} static partial class {catalogName}");

        writer.Line(depth, "{");

        string undeclared =
            format.ApplyToUndeclared(enumType.Name, "value.ToString()");

        WriteStrings(writer, depth + 1, qualified, enumType, members, format);
        writer.Blank();
        WriteCodes(writer, depth + 1, qualified, enumType, members, format);
        writer.Blank();
        WriteErrors(writer, depth + 1, qualified, members);
        writer.Blank();

        WriteLookup(
            writer,
            depth + 1,
            qualified,
            members,
            "string",
            "ToErrorCodeName",
            "error code name",
            member => $"{NamesClass}.{member.Name}",
            undeclared);

        writer.Blank();

        WriteLookup(
            writer,
            depth + 1,
            qualified,
            members,
            ErrorCodeType,
            "ToErrorCode",
            "error code",
            member => $"{CodesClass}.{member.Name}",
            $"new {ErrorCodeType}({undeclared})");

        writer.Blank();
        WriteToError(writer, depth + 1, qualified);

        writer.Line(depth, "}");

        if (@namespace.Length > 0) writer.Line(0, "}");

        return writer.ToString();
    }

    private static void WriteStrings(
        Writer writer,
        int depth,
        string qualified,
        INamedTypeSymbol enumType,
        IReadOnlyList<IFieldSymbol> members,
        ErrorCodeFormat format)
    {
        writer.Line(
            depth,
            $"/// <summary>The error code name of every <c>{qualified}</c> member.</summary>");

        writer.Line(depth, $"public static class {NamesClass}");
        writer.Line(depth, "{");

        for (var i = 0; i < members.Count; i++)
        {
            if (i > 0) writer.Blank();

            string name = members[i].Name;
            string value = format.Apply(enumType.Name, name);

            writer.Line(
                depth + 1,
                $"/// <summary>The error code name of <c>{qualified}.{name}</c>: <c>{XmlText(value)}</c>.</summary>");

            writer.Line(
                depth + 1,
                $"public const string {name} = {Quote(value)};");
        }

        writer.Line(depth, "}");
    }

    private static void WriteCodes(
        Writer writer,
        int depth,
        string qualified,
        INamedTypeSymbol enumType,
        IReadOnlyList<IFieldSymbol> members,
        ErrorCodeFormat format)
    {
        writer.Line(
            depth,
            $"/// <summary>The error code of every <c>{qualified}</c> member.</summary>");

        writer.Line(depth, $"public static class {CodesClass}");
        writer.Line(depth, "{");

        for (var i = 0; i < members.Count; i++)
        {
            if (i > 0) writer.Blank();

            string name = members[i].Name;

            writer.Line(
                depth + 1,
                $"/// <summary>The error code of <c>{qualified}.{name}</c>: <c>{XmlText(format.Apply(enumType.Name, name))}</c>.</summary>");

            writer.Line(
                depth + 1,
                $"public static readonly {ErrorCodeType} {name} = new {ErrorCodeType}({NamesClass}.{name});");
        }

        writer.Line(depth, "}");
    }

    private static void WriteErrors(
        Writer writer,
        int depth,
        string qualified,
        IReadOnlyList<IFieldSymbol> members)
    {
        writer.Line(
            depth,
            $"/// <summary>The error factory of every <c>{qualified}</c> member.</summary>");

        writer.Line(depth, $"public static class {ErrorsClass}");
        writer.Line(depth, "{");

        for (var i = 0; i < members.Count; i++)
        {
            if (i > 0) writer.Blank();

            string name = members[i].Name;

            writer.Line(
                depth + 1,
                $"/// <summary>Creates an error carrying the error code of <c>{qualified}.{name}</c>.</summary>");

            writer.Line(depth + 1, MessageParamDoc);

            writer.Line(depth + 1, "/// <returns>The created error.</returns>");

            writer.Line(
                depth + 1,
                $"public static {ErrorType} {name}(string message)");

            writer.Line(depth + 1, "{");

            writer.Line(
                depth + 2,
                $"return new {ErrorType}({CodesClass}.{name}, message);");

            writer.Line(depth + 1, "}");
        }

        writer.Line(depth, "}");
    }

    private static void WriteLookup(
        Writer writer,
        int depth,
        string qualified,
        IReadOnlyList<IFieldSymbol> members,
        string returnType,
        string methodName,
        string noun,
        Func<IFieldSymbol, string> result,
        string fallback)
    {
        writer.Line(
            depth,
            $"/// <summary>Gets the {noun} of a <c>{qualified}</c> value.</summary>");

        writer.Line(
            depth,
            $"/// <param name=\"value\">The value to read the {noun} of.</param>");

        writer.Line(
            depth,
            $"/// <returns>The {noun}. A value that is not a declared member gets the same scheme applied to its numeric value.</returns>");

        writer.Line(
            depth,
            $"public static {returnType} {methodName}(this {qualified} value)");

        writer.Line(depth, "{");
        writer.Line(depth + 1, "switch (value)");
        writer.Line(depth + 1, "{");

        foreach (IFieldSymbol member in members)
        {
            writer.Line(depth + 2, $"case {qualified}.{member.Name}:");
            writer.Line(depth + 3, $"return {result(member)};");
        }

        writer.Line(depth + 2, "default:");
        writer.Line(depth + 3, $"return {fallback};");
        writer.Line(depth + 1, "}");
        writer.Line(depth, "}");
    }

    private static void WriteToError(Writer writer, int depth, string qualified)
    {
        writer.Line(
            depth,
            $"/// <summary>Creates an error carrying the error code of a <c>{qualified}</c> value.</summary>");

        writer.Line(
            depth,
            "/// <param name=\"value\">The value to read the error code of.</param>");

        writer.Line(depth, MessageParamDoc);

        writer.Line(depth, "/// <returns>The created error.</returns>");

        writer.Line(
            depth,
            $"public static {ErrorType} ToError(this {qualified} value, string message)");

        writer.Line(depth, "{");

        writer.Line(
            depth + 1,
            $"return new {ErrorType}(ToErrorCode(value), message);");

        writer.Line(depth, "}");
    }

    private static string XmlText(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static string Quote(string text) =>
        "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string AccessibilityOf(INamedTypeSymbol enumType) =>
        enumType.DeclaredAccessibility == Accessibility.Public
            ? "public"
            : "internal";

    private sealed class Writer
    {
        private readonly StringBuilder _builder = new StringBuilder();

        public void Line(int depth, string text)
        {
            _builder.Append(new string(' ', depth * 4));
            _builder.Append(text);
            _builder.Append('\n');
        }

        public void Blank() => _builder.Append('\n');

        public override string ToString() => _builder.ToString();
    }
}
