// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Waystone.Monads.Specs.Options.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "option")]
    public partial class FilterExtensionsForAsyncOptionFeature : object, Xunit.IClassFixture<FilterExtensionsForAsyncOptionFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = new string[] {
                "option"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Specs/Options/Features", "Filter Extensions for Async Option", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "FilterExtensions.feature"
#line hidden
        
        public FilterExtensionsForAsyncOptionFeature(FilterExtensionsForAsyncOptionFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Specs/Options/Features/FilterExtensions.feature.ndjson", 14);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Task Option Filter when Some and Async Predicate \"true\"")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Filter Extensions for Async Option")]
        [global::Xunit.TraitAttribute("Description", "Task Option Filter when Some and Async Predicate \"true\"")]
        public async global::System.Threading.Tasks.Task TaskOptionFilterWhenSomeAndAsyncPredicateTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Task Option Filter when Some and Async Predicate \"true\"", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
        await testRunner.GivenAsync("Option is Some with value 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
        await testRunner.AndAsync("Option is wrapped in a Task", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 7
        await testRunner.AndAsync("an async predicate that returns \"true\" for int value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
        await testRunner.WhenAsync("invoking Filter on Option Task with the async predicate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
        await testRunner.ThenAsync("the result Option should be Some with value 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Task Option Filter when Some and Async Predicate \"false\"")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Filter Extensions for Async Option")]
        [global::Xunit.TraitAttribute("Description", "Task Option Filter when Some and Async Predicate \"false\"")]
        public async global::System.Threading.Tasks.Task TaskOptionFilterWhenSomeAndAsyncPredicateFalse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Task Option Filter when Some and Async Predicate \"false\"", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
        await testRunner.GivenAsync("Option is Some with value 20", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
        await testRunner.AndAsync("Option is wrapped in a Task", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
        await testRunner.AndAsync("an async predicate that returns \"false\" for int value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
        await testRunner.WhenAsync("invoking Filter on Option Task with the async predicate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
        await testRunner.ThenAsync("the result Option should be None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Task Option Filter when None")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Filter Extensions for Async Option")]
        [global::Xunit.TraitAttribute("Description", "Task Option Filter when None")]
        public async global::System.Threading.Tasks.Task TaskOptionFilterWhenNone()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Task Option Filter when None", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
        await testRunner.GivenAsync("Option is None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
        await testRunner.AndAsync("Option is wrapped in a Task", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
        await testRunner.AndAsync("an async predicate that returns \"true\" for int value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
        await testRunner.WhenAsync("invoking Filter on Option Task with the async predicate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
        await testRunner.ThenAsync("the result Option should be None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Task Option Filter when Some and Sync Predicate \"true\"")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Filter Extensions for Async Option")]
        [global::Xunit.TraitAttribute("Description", "Task Option Filter when Some and Sync Predicate \"true\"")]
        public async global::System.Threading.Tasks.Task TaskOptionFilterWhenSomeAndSyncPredicateTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Task Option Filter when Some and Sync Predicate \"true\"", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
        await testRunner.GivenAsync("Option is Some with value 25", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
        await testRunner.AndAsync("Option is wrapped in a Task", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
        await testRunner.AndAsync("a sync predicate that returns \"true\" for int value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
        await testRunner.WhenAsync("invoking Filter on Option Task with the sync predicate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
        await testRunner.ThenAsync("the result Option should be Some with value 25", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Task Option Filter when Some and Sync Predicate \"false\"")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Filter Extensions for Async Option")]
        [global::Xunit.TraitAttribute("Description", "Task Option Filter when Some and Sync Predicate \"false\"")]
        public async global::System.Threading.Tasks.Task TaskOptionFilterWhenSomeAndSyncPredicateFalse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Task Option Filter when Some and Sync Predicate \"false\"", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 32
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
        await testRunner.GivenAsync("Option is Some with value 25", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
        await testRunner.AndAsync("Option is wrapped in a Task", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
        await testRunner.AndAsync("a sync predicate that returns \"false\" for int value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
        await testRunner.WhenAsync("invoking Filter on Option Task with the sync predicate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
        await testRunner.ThenAsync("the result Option should be None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Task Option Filter when None and Sync Predicate")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Filter Extensions for Async Option")]
        [global::Xunit.TraitAttribute("Description", "Task Option Filter when None and Sync Predicate")]
        public async global::System.Threading.Tasks.Task TaskOptionFilterWhenNoneAndSyncPredicate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Task Option Filter when None and Sync Predicate", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 40
        await testRunner.GivenAsync("Option is None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
        await testRunner.AndAsync("Option is wrapped in a Task", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
        await testRunner.AndAsync("a sync predicate that returns \"true\" for int value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
        await testRunner.WhenAsync("invoking Filter on Option Task with the sync predicate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
        await testRunner.ThenAsync("the result Option should be None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="ValueTask Option Filter when Some and Predicate \"true\"")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Filter Extensions for Async Option")]
        [global::Xunit.TraitAttribute("Description", "ValueTask Option Filter when Some and Predicate \"true\"")]
        public async global::System.Threading.Tasks.Task ValueTaskOptionFilterWhenSomeAndPredicateTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ValueTask Option Filter when Some and Predicate \"true\"", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
        await testRunner.GivenAsync("Option is Some with value 30", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
        await testRunner.AndAsync("Option is wrapped in a ValueTask", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
        await testRunner.AndAsync("an async predicate that returns \"true\" for int value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
        await testRunner.WhenAsync("invoking Filter on Option ValueTask with the async predicate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
        await testRunner.ThenAsync("the result Option should be Some with value 30", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="ValueTask Option Filter when Some and Predicate \"false\"")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Filter Extensions for Async Option")]
        [global::Xunit.TraitAttribute("Description", "ValueTask Option Filter when Some and Predicate \"false\"")]
        public async global::System.Threading.Tasks.Task ValueTaskOptionFilterWhenSomeAndPredicateFalse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ValueTask Option Filter when Some and Predicate \"false\"", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 54
        await testRunner.GivenAsync("Option is Some with value 40", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
        await testRunner.AndAsync("Option is wrapped in a ValueTask", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
        await testRunner.AndAsync("an async predicate that returns \"false\" for int value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
        await testRunner.WhenAsync("invoking Filter on Option ValueTask with the async predicate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
        await testRunner.ThenAsync("the result Option should be None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="ValueTask Option Filter when None")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Filter Extensions for Async Option")]
        [global::Xunit.TraitAttribute("Description", "ValueTask Option Filter when None")]
        public async global::System.Threading.Tasks.Task ValueTaskOptionFilterWhenNone()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ValueTask Option Filter when None", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
        await testRunner.GivenAsync("Option is None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
        await testRunner.AndAsync("Option is wrapped in a ValueTask", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
        await testRunner.AndAsync("an async predicate that returns \"true\" for int value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
        await testRunner.WhenAsync("invoking Filter on Option ValueTask with the async predicate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
        await testRunner.ThenAsync("the result Option should be None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="ValueTask Option Filter when Some and Sync Predicate \"true\"")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Filter Extensions for Async Option")]
        [global::Xunit.TraitAttribute("Description", "ValueTask Option Filter when Some and Sync Predicate \"true\"")]
        public async global::System.Threading.Tasks.Task ValueTaskOptionFilterWhenSomeAndSyncPredicateTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ValueTask Option Filter when Some and Sync Predicate \"true\"", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
        await testRunner.GivenAsync("Option is Some with value 50", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
        await testRunner.AndAsync("Option is wrapped in a ValueTask", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
        await testRunner.AndAsync("a sync predicate that returns \"true\" for int value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
        await testRunner.WhenAsync("invoking Filter on Option ValueTask with the sync predicate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 72
        await testRunner.ThenAsync("the result Option should be Some with value 50", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="ValueTask Option Filter when Some and Sync Predicate \"false\"")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Filter Extensions for Async Option")]
        [global::Xunit.TraitAttribute("Description", "ValueTask Option Filter when Some and Sync Predicate \"false\"")]
        public async global::System.Threading.Tasks.Task ValueTaskOptionFilterWhenSomeAndSyncPredicateFalse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ValueTask Option Filter when Some and Sync Predicate \"false\"", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 74
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
        await testRunner.GivenAsync("Option is Some with value 60", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 76
        await testRunner.AndAsync("Option is wrapped in a ValueTask", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
        await testRunner.AndAsync("a sync predicate that returns \"false\" for int value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
        await testRunner.WhenAsync("invoking Filter on Option ValueTask with the sync predicate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
        await testRunner.ThenAsync("the result Option should be None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="ValueTask Option Filter when None and Sync Predicate")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Filter Extensions for Async Option")]
        [global::Xunit.TraitAttribute("Description", "ValueTask Option Filter when None and Sync Predicate")]
        public async global::System.Threading.Tasks.Task ValueTaskOptionFilterWhenNoneAndSyncPredicate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ValueTask Option Filter when None and Sync Predicate", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 81
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 82
        await testRunner.GivenAsync("Option is None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 83
        await testRunner.AndAsync("Option is wrapped in a ValueTask", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
        await testRunner.AndAsync("a sync predicate that returns \"true\" for int value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
        await testRunner.WhenAsync("invoking Filter on Option ValueTask with the sync predicate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
        await testRunner.ThenAsync("the result Option should be None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await FilterExtensionsForAsyncOptionFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await FilterExtensionsForAsyncOptionFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
