namespace Waystone.Monads.Schemas.SourceGenerators;

using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

internal static class SchemaInstanceWriter
{
    public const string InstanceMember = "Instance";

    private const string AutoGeneratedHeader = "// <auto-generated/>";

    public static string Emit(
        INamedTypeSymbol schema,
        IReadOnlyList<INamedTypeSymbol> containers)
    {
        string qualified =
            schema.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        string @namespace = schema.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : schema.ContainingNamespace.ToDisplayString();

        var writer = new Writer();

        writer.Line(0, AutoGeneratedHeader);
        writer.Blank();

        var depth = 0;

        if (@namespace.Length > 0)
        {
            writer.Line(0, "namespace " + @namespace);
            writer.Line(0, "{");
            depth = 1;
        }

        foreach (INamedTypeSymbol container in containers)
        {
            writer.Line(depth, Declaration(container));
            writer.Line(depth, "{");
            depth++;
        }

        writer.Line(depth, Declaration(schema));
        writer.Line(depth, "{");

        WriteInstance(writer, depth + 1, schema, qualified);

        writer.Line(depth, "}");

        while (depth > 0)
        {
            depth--;
            writer.Line(depth, "}");
        }

        return writer.ToString();
    }

    private static void WriteInstance(
        Writer writer,
        int depth,
        INamedTypeSymbol schema,
        string qualified)
    {
        writer.Line(
            depth,
            "/// <summary>The shared <c>" + schema.Name + "</c>.</summary>");

        writer.Line(
            depth,
            "/// <remarks>A schema holds nothing that belongs to one parse, so a single instance serves every call. Reach for this rather than constructing another, including where a schema is the item of a list or a field of an enclosing schema.</remarks>");

        writer.Line(
            depth,
            AccessibilityOf(schema)
          + " static "
          + qualified
          + " "
          + InstanceMember
          + " { get; } = new "
          + qualified
          + "();");
    }

    /// <summary>
    /// The reopening declaration, with no accessibility and no constraints. A
    /// partial declaration may omit both, and repeating either only creates a
    /// second place they can disagree.
    /// </summary>
    private static string Declaration(INamedTypeSymbol type)
    {
        var declaration = new StringBuilder("partial ");

        declaration.Append(KeywordOf(type));
        declaration.Append(' ');
        declaration.Append(type.Name);

        if (type.TypeParameters.Length == 0) return declaration.ToString();

        declaration.Append('<');

        for (var index = 0; index < type.TypeParameters.Length; index++)
        {
            if (index > 0) declaration.Append(", ");

            declaration.Append(type.TypeParameters[index].Name);
        }

        declaration.Append('>');

        return declaration.ToString();
    }

    private static string KeywordOf(INamedTypeSymbol type)
    {
        if (type.TypeKind == TypeKind.Interface) return "interface";

        if (type.TypeKind == TypeKind.Struct)
        {
            return type.IsRecord ? "record struct" : "struct";
        }

        return type.IsRecord ? "record" : "class";
    }

    private static string AccessibilityOf(INamedTypeSymbol schema) =>
        schema.DeclaredAccessibility == Accessibility.Public
            ? "public"
            : "internal";

    private sealed class Writer
    {
        private readonly StringBuilder _builder = new StringBuilder();

        public void Line(int depth, string text)
        {
            _builder.Append(' ', depth * 4);
            _builder.Append(text);
            _builder.Append('\n');
        }

        public void Blank() => _builder.Append('\n');

        public override string ToString() => _builder.ToString();
    }
}
