namespace Waystone.SourceGenerators.AwaitedReceivers;

internal static class GeneratedAttributes
{
    public const string ReceiversAttributeMetadataName =
        "Waystone.SourceGenerators.GenerateAwaitedReceiversAttribute";

    public const string MemberAttributeMetadataName =
        "Waystone.SourceGenerators.GenerateAwaitedMemberAttribute";

    public const string HintName = "GenerateAwaitedReceiversAttribute.g.cs";

    public const string Source = """
        // <auto-generated/>
        #nullable enable

        namespace Waystone.SourceGenerators
        {
            /// <summary>
            /// Marks a static partial class as the destination for generated
            /// <c>Task&lt;TReceiver&gt;</c> and <c>ValueTask&lt;TReceiver&gt;</c> extension
            /// blocks, whose members await the receiver and then forward to the source
            /// member.
            /// </summary>
            /// <remarks>
            /// Every extension block the class declares over an unawaited receiver is
            /// generated in both awaited shapes. To also generate a shape for one of the
            /// receiver type's own instance methods, add a
            /// <see cref="GenerateAwaitedMemberAttribute" /> naming it.
            /// </remarks>
            [System.AttributeUsage(System.AttributeTargets.Class)]
            [System.CodeDom.Compiler.GeneratedCode("Waystone.SourceGenerators", null)]
            internal sealed class GenerateAwaitedReceiversAttribute : System.Attribute
            {
                /// <summary>
                /// Marks a static partial class as the destination for generated awaited
                /// receiver shapes.
                /// </summary>
                /// <param name="receiver">
                /// The unbound receiver type whose awaited shapes are generated, for
                /// example <c>typeof(Option&lt;&gt;)</c>.
                /// </param>
                public GenerateAwaitedReceiversAttribute(System.Type receiver)
                {
                    Receiver = receiver;
                }

                /// <summary>The unbound receiver type whose awaited shapes are generated.</summary>
                public System.Type Receiver { get; }
            }

            /// <summary>
            /// Generates awaited shapes for one of the receiver type's own instance
            /// methods. Apply once per method; every overload of the named method is
            /// covered.
            /// </summary>
            [System.AttributeUsage(
                System.AttributeTargets.Class,
                AllowMultiple = true)]
            [System.CodeDom.Compiler.GeneratedCode("Waystone.SourceGenerators", null)]
            internal sealed class GenerateAwaitedMemberAttribute : System.Attribute
            {
                /// <summary>
                /// Generates awaited shapes for a method of the receiver type.
                /// </summary>
                /// <param name="member">
                /// The name of the receiver type's public instance method to generate
                /// shapes for.
                /// </param>
                public GenerateAwaitedMemberAttribute(string member)
                {
                    Member = member;
                }

                /// <summary>The receiver type's method the shapes are generated from.</summary>
                public string Member { get; }

                /// <summary>
                /// Replaces the generated <c>&lt;summary&gt;</c> instead of prefixing the
                /// source member's summary with the await phrasing. Every other
                /// documentation tag is still forwarded from the source member. Applies to
                /// every overload of <see cref="Member" />.
                /// </summary>
                public string? Summary { get; set; }
            }
        }

        """;
}
