<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latestMajor</LangVersion>
        <NoWarn>CS1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <Title>Waystone.Monads</Title>
        <Description>A .NET implementation of the Rust std::option and std::result types</Description>
        <PackageTags>result pattern option monad aspnetcore rust error handling framework</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);PackMonadAnalyzers</TargetsForTfmSpecificContentInPackage>
    </PropertyGroup>

    <Import Project="..\Waystone.Monads.Analyzers\Waystone.Monads.Analyzers.props"/>
    <Import Project="..\Waystone.Monads.SourceGenerators\Waystone.Monads.SourceGenerators.props"/>
    <Import Project="..\Waystone.SourceGenerators\Waystone.SourceGenerators.props"/>

    <Target Name="PackMonadAnalyzers" DependsOnTargets="ResolveProjectReferences">
        <ItemGroup>
            <TfmSpecificPackageFile Include="@(Analyzer)"
                                    Condition="'%(Filename)' == 'Waystone.Monads.Analyzers' or '%(Filename)' == 'Waystone.Monads.Analyzers.CodeFixes' or '%(Filename)' == 'Waystone.Monads.SourceGenerators'"
                                    PackagePath="analyzers/dotnet/cs"/>
        </ItemGroup>
    </Target>

    <ItemGroup>
        <AdditionalFiles Include="PublicAPI.Shipped.txt"/>
        <AdditionalFiles Include="PublicAPI.Unshipped.txt"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="PolySharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.Threading.Tasks.Extensions"/>
        <PackageReference Include="System.ValueTuple"/>
    </ItemGroup>
</Project>
