<Project>
    <ItemGroup Label="Load the Waystone source generators into the importing project's build">
        <ProjectReference Include="$(MSBuildThisFileDirectory)Waystone.Internal.SourceGenerators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
    </ItemGroup>
</Project>
