namespace Waystone.Internal.SourceGenerators.AwaitedReceivers;

internal static class GeneratedAttributes
{
    public const string ReceiversAttributeMetadataName =
        "Waystone.Internal.SourceGenerators.GenerateAwaitedReceiversAttribute";

    public const string MemberAttributeMetadataName =
        "Waystone.Internal.SourceGenerators.GenerateAwaitedMemberAttribute";

    public const string ExcludeAttributeMetadataName =
        "Waystone.Internal.SourceGenerators.ExcludeFromAwaitedReceiversAttribute";

    public const string HintName = "GenerateAwaitedReceiversAttribute.g.cs";

    public const string Source = """
        // <auto-generated/>
        #nullable enable

        namespace Waystone.Internal.SourceGenerators
        {
            /// <summary>
            /// Marks a static partial class as the destination for generated
            /// <c>Task&lt;TReceiver&gt;</c> and <c>ValueTask&lt;TReceiver&gt;</c> extension
            /// blocks, whose members await the receiver and then forward to the source
            /// member.
            /// </summary>
            /// <remarks>
            /// Every public extension member the class declares over a non-awaitable
            /// receiver is generated in both awaited shapes, whatever that receiver's
            /// type is — the constructor's type filters nothing here. Each generated
            /// member takes the source member's name with <c>Async</c> appended, unless
            /// it already ends in <c>Async</c>, and always returns <c>ValueTask</c> or
            /// <c>ValueTask&lt;T&gt;</c>, including inside the <c>Task</c> block.
            /// <para>
            /// To also generate shapes for one of the receiver type's own instance
            /// methods, add a <see cref="GenerateAwaitedMemberAttribute" /> naming it.
            /// Those lookups are the only use of the constructor's type.
            /// </para>
            /// <para>
            /// The class must be declared <c>partial</c>; the generator reports
            /// <c>WSG0001</c> and emits nothing otherwise. Apply this once per class —
            /// it is not <c>AllowMultiple</c>, so a class has exactly one receiver type.
            /// </para>
            /// </remarks>
            [System.AttributeUsage(System.AttributeTargets.Class)]
            [System.CodeDom.Compiler.GeneratedCode("Waystone.Internal.SourceGenerators", null)]
            internal sealed class GenerateAwaitedReceiversAttribute : System.Attribute
            {
                /// <summary>
                /// Marks a static partial class as the destination for generated awaited
                /// receiver shapes.
                /// </summary>
                /// <param name="receiver">
                /// The unbound receiver type that
                /// <see cref="GenerateAwaitedMemberAttribute" /> names are resolved
                /// against, for example <c>typeof(Option&lt;&gt;)</c>.
                /// </param>
                public GenerateAwaitedReceiversAttribute(System.Type receiver)
                {
                    Receiver = receiver;
                }

                /// <summary>
                /// The unbound receiver type that
                /// <see cref="GenerateAwaitedMemberAttribute" /> names are resolved
                /// against, for example <c>typeof(Option&lt;&gt;)</c>.
                /// </summary>
                public System.Type Receiver { get; }

                /// <summary>
                /// The name to give the awaited receiver on every generated
                /// <c>extension</c> block, in place of the source receiver's name
                /// with <c>Task</c> appended.
                /// </summary>
                /// <remarks>
                /// Set this only to keep an existing name. A receiver parameter is
                /// part of the public API baseline and renaming one is
                /// source-breaking for a caller who passes it by name in static
                /// invocation syntax, so a class whose awaited shapes were
                /// hand-written before they were generated has to pin whatever they
                /// were called. There is nothing to preserve on a new class; leave
                /// it unset and take the default. Default:
                /// <see langword="null" />.
                /// <para>
                /// Pinning the source receiver's own name is the ordinary case and
                /// is allowed: the local holding the awaited value is called
                /// <c>awaited</c> rather than taking that name, so the two cannot
                /// collide.
                /// </para>
                /// </remarks>
                public string? ReceiverParameterName { get; set; }
            }

            /// <summary>
            /// Generates awaited shapes for one of the receiver type's own instance
            /// methods. Apply once per method; every overload of the named method is
            /// covered.
            /// </summary>
            /// <remarks>
            /// Only public, non-static, ordinary methods match, so properties, operators
            /// and static factories cannot be named. A name that matches none of them
            /// reports <c>WSG0002</c>. This attribute is read only on a class that also
            /// carries <see cref="GenerateAwaitedReceiversAttribute" />; on its own it
            /// does nothing. Write the name with <c>nameof</c> so a rename fails the
            /// build.
            /// </remarks>
            [System.AttributeUsage(
                System.AttributeTargets.Class,
                AllowMultiple = true)]
            [System.CodeDom.Compiler.GeneratedCode("Waystone.Internal.SourceGenerators", null)]
            internal sealed class GenerateAwaitedMemberAttribute : System.Attribute
            {
                /// <summary>
                /// Generates awaited shapes for a method of the receiver type.
                /// </summary>
                /// <param name="member">
                /// The name of the receiver type's public instance method to generate
                /// shapes for.
                /// </param>
                public GenerateAwaitedMemberAttribute(string member)
                {
                    Member = member;
                }

                /// <summary>The receiver type's method the shapes are generated from.</summary>
                public string Member { get; }

                /// <summary>
                /// The summary to write on the generated members, in place of the source
                /// member's own summary prefixed with the await phrasing.
                /// </summary>
                /// <remarks>
                /// Every other documentation tag is still forwarded from the source
                /// member, and this applies to every overload of
                /// <see cref="Member" />. Setting it is also the only way to document a
                /// generated member whose source member carries no doc comment. Default:
                /// <see langword="null" />, meaning the source member's own summary is
                /// used.
                /// </remarks>
                public string? Summary { get; set; }
            }

            /// <summary>
            /// Keeps one public extension member off the generated awaited
            /// receivers.
            /// </summary>
            /// <remarks>
            /// The lift <see cref="GenerateAwaitedReceiversAttribute" /> performs is
            /// blanket and needs no opt-in, so a member whose awaited shape is
            /// meaningless still gets one. A member returning a builder or a state
            /// binder is the usual case: the awaited form hands back a task of a
            /// thing the caller cannot chain, and the pair costs two public members
            /// and the baseline rows that lock them. This is the only way to
            /// decline it.
            /// <para>
            /// Weigh it against what it removes. A caller holding a
            /// <c>Task&lt;TReceiver&gt;</c> must await first and then call the
            /// member, so the excluded member is one they can no longer reach in a
            /// single chain.
            /// </para>
            /// <para>
            /// It reads only on a public extension member of a class carrying
            /// <see cref="GenerateAwaitedReceiversAttribute" />, and is inert
            /// anywhere else rather than reported. That includes a receiver-type
            /// method named by <see cref="GenerateAwaitedMemberAttribute" /> —
            /// those are opt-in already, so leave the name off the list instead.
            /// </para>
            /// </remarks>
            [System.AttributeUsage(System.AttributeTargets.Method)]
            [System.CodeDom.Compiler.GeneratedCode("Waystone.Internal.SourceGenerators", null)]
            internal sealed class ExcludeFromAwaitedReceiversAttribute
                : System.Attribute
            {
            }
        }

        """;
}
