namespace Waystone.Monads.SourceGenerators;

using System.Linq;
using Microsoft.CodeAnalysis.CSharp;
using Shouldly;
using Xunit;

public sealed class ErrorCodeCatalogGeneratorTests
{
    private const string OneMemberEnum = """
        [ErrorCodeCatalog]
        public enum OrderError
        {
            NotFound,
        }
        """;

    [Fact]
    public void AnnotatesTheCatalogWhenTheConsumerCanReadAnnotations()
    {
        GeneratorRun run = Verify.RunAtLanguageVersion(
            LanguageVersion.CSharp8,
            OneMemberEnum);

        run.GeneratorDiagnostics.ShouldBeEmpty();
        run.Source.ShouldNotBeNull();

        run.Source.ShouldContain("#nullable enable");
    }

    [Fact]
    public void LeavesTheCatalogUnannotatedBelowCSharp8()
    {
        GeneratorRun run = Verify.RunAtLanguageVersion(
            LanguageVersion.CSharp7_3,
            OneMemberEnum);

        run.GeneratorDiagnostics.ShouldBeEmpty();
        run.Source.ShouldNotBeNull();

        run.Source.ShouldNotContain("#nullable");
    }

    [Fact]
    public void GeneratesTheWholeProviderForATwoMemberEnum()
    {
        GeneratorRun run = Verify.Run(
            """
            [ErrorCodeCatalog]
            public enum OrderError
            {
                NotFound,
                AlreadyShipped,
            }
            """);

        run.CompilationDiagnostics.ShouldBeEmpty();
        run.GeneratorDiagnostics.ShouldBeEmpty();

        run.Source.ShouldBe(
            """
            // <auto-generated/>

            #nullable enable

            namespace Sample
            {
                /// <summary>The error code names, error codes and error factories of <c>global::Sample.OrderError</c>.</summary>
                public static partial class OrderErrorCatalog
                {
                    /// <summary>The error code name of every <c>global::Sample.OrderError</c> member.</summary>
                    public static class Names
                    {
                        /// <summary>The error code name of <c>global::Sample.OrderError.NotFound</c>: <c>OrderError.NotFound</c>.</summary>
                        public const string NotFound = "OrderError.NotFound";

                        /// <summary>The error code name of <c>global::Sample.OrderError.AlreadyShipped</c>: <c>OrderError.AlreadyShipped</c>.</summary>
                        public const string AlreadyShipped = "OrderError.AlreadyShipped";
                    }

                    /// <summary>The error code of every <c>global::Sample.OrderError</c> member.</summary>
                    public static class Codes
                    {
                        /// <summary>The error code of <c>global::Sample.OrderError.NotFound</c>: <c>OrderError.NotFound</c>.</summary>
                        public static readonly global::Waystone.Monads.Results.Errors.ErrorCode NotFound = new global::Waystone.Monads.Results.Errors.ErrorCode(Names.NotFound);

                        /// <summary>The error code of <c>global::Sample.OrderError.AlreadyShipped</c>: <c>OrderError.AlreadyShipped</c>.</summary>
                        public static readonly global::Waystone.Monads.Results.Errors.ErrorCode AlreadyShipped = new global::Waystone.Monads.Results.Errors.ErrorCode(Names.AlreadyShipped);
                    }

                    /// <summary>The error factory of every <c>global::Sample.OrderError</c> member.</summary>
                    public static class Errors
                    {
                        /// <summary>Creates an error carrying the error code of <c>global::Sample.OrderError.NotFound</c>.</summary>
                        /// <param name="message">The message describing this occurrence of the error. Trimmed of surrounding whitespace; a message that is null, empty or whitespace is replaced by the fallback configured through <c>MonadOptions.UseFallbackErrorMessage</c> rather than rejected.</param>
                        /// <returns>The created error.</returns>
                        public static global::Waystone.Monads.Results.Errors.Error NotFound(string message)
                        {
                            return new global::Waystone.Monads.Results.Errors.Error(Codes.NotFound, message);
                        }

                        /// <summary>Creates an error carrying the error code of <c>global::Sample.OrderError.AlreadyShipped</c>.</summary>
                        /// <param name="message">The message describing this occurrence of the error. Trimmed of surrounding whitespace; a message that is null, empty or whitespace is replaced by the fallback configured through <c>MonadOptions.UseFallbackErrorMessage</c> rather than rejected.</param>
                        /// <returns>The created error.</returns>
                        public static global::Waystone.Monads.Results.Errors.Error AlreadyShipped(string message)
                        {
                            return new global::Waystone.Monads.Results.Errors.Error(Codes.AlreadyShipped, message);
                        }
                    }

                    /// <summary>Gets the error code name of a <c>global::Sample.OrderError</c> value.</summary>
                    /// <param name="value">The value to read the error code name of.</param>
                    /// <returns>The error code name. A value that is not a declared member gets the same scheme applied to its numeric value.</returns>
                    public static string ToErrorCodeName(this global::Sample.OrderError value)
                    {
                        switch (value)
                        {
                            case global::Sample.OrderError.NotFound:
                                return Names.NotFound;
                            case global::Sample.OrderError.AlreadyShipped:
                                return Names.AlreadyShipped;
                            default:
                                return "OrderError." + value.ToString();
                        }
                    }

                    /// <summary>Gets the error code of a <c>global::Sample.OrderError</c> value.</summary>
                    /// <param name="value">The value to read the error code of.</param>
                    /// <returns>The error code. A value that is not a declared member gets the same scheme applied to its numeric value.</returns>
                    public static global::Waystone.Monads.Results.Errors.ErrorCode ToErrorCode(this global::Sample.OrderError value)
                    {
                        switch (value)
                        {
                            case global::Sample.OrderError.NotFound:
                                return Codes.NotFound;
                            case global::Sample.OrderError.AlreadyShipped:
                                return Codes.AlreadyShipped;
                            default:
                                return new global::Waystone.Monads.Results.Errors.ErrorCode("OrderError." + value.ToString());
                        }
                    }

                    /// <summary>Creates an error carrying the error code of a <c>global::Sample.OrderError</c> value.</summary>
                    /// <param name="value">The value to read the error code of.</param>
                    /// <param name="message">The message describing this occurrence of the error. Trimmed of surrounding whitespace; a message that is null, empty or whitespace is replaced by the fallback configured through <c>MonadOptions.UseFallbackErrorMessage</c> rather than rejected.</param>
                    /// <returns>The created error.</returns>
                    public static global::Waystone.Monads.Results.Errors.Error ToError(this global::Sample.OrderError value, string message)
                    {
                        return new global::Waystone.Monads.Results.Errors.Error(ToErrorCode(value), message);
                    }
                }
            }

            """.Replace("\r\n", "\n"));
    }

    [Theory]
    [InlineData("OrderError", "OrderErrorCatalog")]
    [InlineData("OrderErrorCode", "OrderErrorCodeCatalog")]
    [InlineData("PaymentFailure", "PaymentFailureCatalog")]
    [InlineData("Error", "ErrorCatalog")]
    public void NamesTheCatalogAfterTheEnum(string name, string expected)
    {
        GeneratorRun run = Verify.Run(
            $$"""
            [ErrorCodeCatalog]
            public enum {{name}}
            {
                NotFound,
            }
            """);

        run.CompilationDiagnostics.ShouldBeEmpty();
        run.Source.ShouldContain($"static partial class {expected}");
    }

    [Fact]
    public void EmitsTheDefaultSchemeForEveryMember()
    {
        Verify.Run(
                """
                [ErrorCodeCatalog]
                public enum OrderError
                {
                    NotFound,
                }
                """)
              .Source.ShouldContain("= \"OrderError.NotFound\";");
    }

    [Fact]
    public void GeneratesNothingWithoutTheAttribute()
    {
        GeneratorRun run = Verify.Run(
            """
            public enum OrderError
            {
                NotFound,
            }
            """);

        run.HintNames.ShouldBeEmpty();
        run.Source.ShouldBeEmpty();
        run.GeneratorDiagnostics.ShouldBeEmpty();
    }

    [Fact]
    public void EmitsAHintNameThatIsTreatedAsGeneratedCode()
    {
        GeneratorRun run = Verify.Run(
            """
            [ErrorCodeCatalog]
            public enum OrderError
            {
                NotFound,
            }
            """);

        string hintName = run.HintNames.ShouldHaveSingleItem();

        hintName.ShouldEndWith(".g.cs");

        run.Source.ShouldContain("// <auto-generated/>");
    }

    [Fact]
    public void CarriesTheEnumsNamespaceAndAccessibility()
    {
        Verify.Run(
                  """
                  [ErrorCodeCatalog]
                  internal enum OrderError
                  {
                      NotFound,
                  }
                  """)
              .Source.ShouldContain("internal static partial class OrderErrorCatalog");
    }

    [Fact]
    public void EmitsNormalisedLineEndings()
    {
        GeneratorRun run = Verify.Run(
            """
            [ErrorCodeCatalog]
            public enum OrderError
            {
                NotFound,
            }
            """);

        run.Generated.ShouldNotBeNull().ShouldNotContain("\r\n");
    }

    [Fact]
    public void ProducesTheSameSourceOnASecondRun()
    {
        (string first, string second) = Verify.RunTwice(
            """
            [ErrorCodeCatalog]
            public enum OrderError
            {
                NotFound,
            }
            """);

        second.ShouldBe(first);
        first.ShouldContain("OrderErrorCatalog");
    }

    [Fact]
    public void RebuildsWhenTheEnumChanges()
    {
        (string first, string second) = Verify.RunTwice(
            """
            [ErrorCodeCatalog]
            public enum OrderError
            {
                NotFound,
            }
            """,
            """
            [ErrorCodeCatalog]
            public enum OrderError
            {
                NotFound,
                AlreadyShipped,
            }
            """);

        second.ShouldNotBe(first);
        second.ShouldContain("AlreadyShipped");
    }

    [Fact]
    public void ReportsAFlagsEnum()
    {
        GeneratorRun run = Verify.Run(
            """
            [ErrorCodeCatalog]
            [Flags]
            public enum OrderError
            {
                NotFound = 1,
                AlreadyShipped = 2,
            }
            """);

        run.DiagnosticIds.ShouldBe(["WMG0001"]);
        run.Source.ShouldBeEmpty();

        run.GeneratorDiagnostics.Single()
           .Severity.ShouldBe(Microsoft.CodeAnalysis.DiagnosticSeverity.Error);
    }

    [Fact]
    public void ReportsAnAliasedValue()
    {
        GeneratorRun run = Verify.Run(
            """
            [ErrorCodeCatalog]
            public enum OrderError
            {
                NotFound = 1,
                Missing = 1,
            }
            """);

        run.DiagnosticIds.ShouldBe(["WMG0002"]);
        run.Source.ShouldBeEmpty();

        run.GeneratorDiagnostics.Single()
           .GetMessage()
           .ShouldContain("'NotFound' and 'Missing' share the value 1");
    }

    [Theory]
    [InlineData("Names")]
    [InlineData("Codes")]
    [InlineData("Errors")]
    public void ReportsAMemberNamedAfterAGeneratedType(string name)
    {
        GeneratorRun run = Verify.Run(
            $$"""
            [ErrorCodeCatalog]
            public enum OrderError
            {
                {{name}},
            }
            """);

        run.DiagnosticIds.ShouldBe(["WMG0003"]);
        run.Source.ShouldBeEmpty();
    }

    /// <summary>
    /// The extensions live on the outer class and the members on the nested ones, so
    /// a member named after an extension is in a different container and does not
    /// collide. Asserted rather than assumed, because it is the reason WMG0003 covers
    /// the three nested class names and not the three extension names.
    /// </summary>
    [Theory]
    [InlineData("ToErrorCodeName")]
    [InlineData("ToErrorCode")]
    [InlineData("ToError")]
    public void AcceptsAMemberNamedAfterAnExtension(string name)
    {
        GeneratorRun run = Verify.Run(
            $$"""
            [ErrorCodeCatalog]
            public enum OrderError
            {
                {{name}},
            }
            """);

        run.GeneratorDiagnostics.ShouldBeEmpty();
        run.CompilationDiagnostics.ShouldBeEmpty();
        run.Source.ShouldContain($"public const string {name} =");
    }

    [Fact]
    public void ReportsTheErrorTypesBeingUnresolvable()
    {
        GeneratorRun run = Verify.RunWithoutMonads(
            """
            [Waystone.Monads.Results.Errors.ErrorCodeCatalog]
            public enum OrderError
            {
                NotFound,
            }
            """);

        run.DiagnosticIds.ShouldBe(["WMG0004"]);
        run.Source.ShouldBeEmpty();

        run.GeneratorDiagnostics.Single()
           .GetMessage()
           .ShouldContain("Waystone.Monads.Results.Errors.ErrorCode");
    }

    private static class Fixture
    {
        internal enum OrderError
        {
            NotFound,
        }
    }
}
