<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latestMajor</LangVersion>
        <Nullable>enable</Nullable>
        <RootNamespace>Microsoft.Extensions.DependencyInjection</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <Title>Waystone.Monads.Extensions.DependencyInjection</Title>
        <Description>
            Authors the ambient Waystone.Monads configuration from a dependency injection container, installing it once when the service provider is ready.
        </Description>
        <PackageTags>result pattern option monad aspnetcore rust error handling framework dependency injection configuration</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="PublicAPI.Shipped.txt"/>
        <AdditionalFiles Include="PublicAPI.Unshipped.txt"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
        <PackageReference Include="PolySharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Waystone.Monads.Extensions.Logging\Waystone.Monads.Extensions.Logging.csproj"/>
        <ProjectReference Include="..\Waystone.Monads\Waystone.Monads.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>
