name: Pull Request

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      
      - name: Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        env:
          ASPNETCORE_ENVIRONMENT: Test
        run: dotnet test --no-restore --collect:"XPlat Code Coverage"

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}