<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latestMajor</LangVersion>
        <ImplicitUsings>disable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <RootNamespace>Waystone.Monads.Analyzers</RootNamespace>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Waystone.Monads\Waystone.Monads.csproj"/>
        <ProjectReference Include="..\..\src\Waystone.Monads.Analyzers\Waystone.Monads.Analyzers.csproj"/>
        <ProjectReference Include="..\..\src\Waystone.Monads.Analyzers.CodeFixes\Waystone.Monads.Analyzers.CodeFixes.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" VersionOverride="5.6.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" VersionOverride="5.6.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Shouldly"/>
        <PackageReference Include="xunit.v3"/>
    </ItemGroup>

</Project>
